#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
    path: /
    controller: App\Controller\HomeController::index
news:
    path: /news
    controller: App\Controller\NewsController::index